version: '3.7'
services:
  nginx:
    image: nginx:1.17.7-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - './app/symfony-app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}