security:
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$S0d5bFdTLi9oMG9vNENEVw$t159J6wyvwClwmDo2gGKx2LaTAEn+rz8K2VV64tz9WE', roles: ['ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
